#!/bin/sh

PORT_START=60000
PORT_END=60020
 
MOSH_DIR=~/.mosh_wrapper
PORTS=$(seq ${PORT_START} ${PORT_END})
MOSH_COMMAND="mosh-client"
 
MY_UID=$(id -u)

DEFAULT_SERVER=dev

if [ -n "${1}" ]; then
	DEFAULT_SERVER=${1}
fi

if [ -z "${DEFAULT_SERVER}" ]; then
	echo "usage: $0 <server> (or specify DEFAULT_SERVER in the script)"
	exit 1
fi

if [ ! -d ${MOSH_DIR} ]; then
    mkdir ${MOSH_DIR}
fi
 
port_to_use=""
for port in ${PORTS}; do
    portfile=${MOSH_DIR}/port-${port}
 
    if [ -e ${portfile} ]; then
        pid=`cat ${portfile}`
        uid_command=`ps -p ${pid} -o "uid=,comm=" || true`
        if [ -z "${uid_command}" ]; then
            # process does not exist
            rm -f ${portfile}
        else
			uid=$(echo ${uid_command} | awk '{ print $1 }')
			command=$(echo ${uid_command} | awk '{ print $2 }')
            if [ "${command}" = "${MOSH_COMMAND}" ]; then
                # pid does not exist
                rm -f ${portfile}
            fi
            if [[ ${uid} != ${MY_UID} ]]; then
                # Not my process!
                rm -f ${portfile}
            fi
        fi
    fi
 
    if [ ! -e ${portfile} ]; then
        port_to_use=${port}
        echo $$ > ${portfile}
        break
    fi
done
 
if [ -n "${port_to_use}" ]; then
	MOSH_OPTS="-p ${port_to_use}"
	oldifs=${IFS}
	IFS=''
	for line in $(host ${DEFAULT_SERVER}); do
		if echo "${line}" | grep -q "has IPv6 address"; then
			MOSH_OPTS="-6 ${MOSH_OPTS}"
			break
		fi
	done
	IFS=${oldifs}
    exec mosh ${MOSH_OPTS} ${DEFAULT_SERVER}
else
    echo "No unused ports to use"
    exit 1
fi
